### ISSUE TITLE
非常感谢你的开源。然后提个意见

### ISSUE THREAD

**Issue by andansky** [pantrif/EasySplashScreen#3]
要是能弄成预加载的就好，就比如说我现在设置成4秒跳转，在这4秒内其时已经跳转到要加载的页面去加载数据了，而不是过了4秒再跳转过去加载数据呢。

**Comment by pantrif** [comment]
Please write your issue in English. I don't know Chinese.

**Comment by andansky** [comment]
Sorry,I mean It is perfect that make it  loading in advance.That is to say,it should jump page first , then splash screen.not splash screen then jump page。

**Comment by pantrif** [comment]
Hello, the purpose of splash screen is to open on start before anything else.
